
// This file has been generated by the GUI designer. Do not modify.
namespace cSharphomework2
{
	public partial class Window1
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.VPaned vpaned1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview1;

		private global::Gtk.EventBox eventbox1;

		private global::Gtk.Table table6;

		private global::Gtk.Button button3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView textview6;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.TextView textview7;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button button4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget cSharphomework2.Window1
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "cSharphomework2.Window1";
			this.Title = global::Mono.Unix.Catalog.GetString("Window1");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child cSharphomework2.Window1.Gtk.Container+ContainerChild
			this.vpaned1 = new global::Gtk.VPaned();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 109;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.Buffer.Text = "Problem 1.Sort Array of Numbers\nWrite a program to sort an array of numbers and t" +
				"hen print them back on the console.\nThe numbers should be entered from the conso" +
				"le on a single line, separated by a space.";
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.textview1.CursorVisible = false;
			this.textview1.AcceptsTab = false;
			this.textview1.Justification = ((global::Gtk.Justification)(2));
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(2));
			this.textview1.PixelsBelowLines = 5;
			this.GtkScrolledWindow.Add(this.textview1);
			this.vpaned1.Add(this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.GtkScrolledWindow]));
			w3.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.eventbox1 = new global::Gtk.EventBox();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.table6 = new global::Gtk.Table(((uint)(2)), ((uint)(3)), false);
			this.table6.Name = "table6";
			this.table6.RowSpacing = ((uint)(6));
			this.table6.ColumnSpacing = ((uint)(6));
			// Container child table6.Gtk.Table+TableChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Sort");
			global::Gtk.Image w4 = new global::Gtk.Image();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.button3.Image = w4;
			this.table6.Add(this.button3);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table6[this.button3]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table6.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textview6 = new global::Gtk.TextView();
			this.textview6.CanFocus = true;
			this.textview6.Name = "textview6";
			this.GtkScrolledWindow1.Add(this.textview6);
			this.table6.Add(this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table6[this.GtkScrolledWindow1]));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.textview7 = new global::Gtk.TextView();
			this.textview7.CanFocus = true;
			this.textview7.Name = "textview7";
			this.textview7.Editable = false;
			this.textview7.CursorVisible = false;
			this.GtkScrolledWindow2.Add(this.textview7);
			this.table6.Add(this.GtkScrolledWindow2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table6[this.GtkScrolledWindow2]));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString("Ok");
			global::Gtk.Image w10 = new global::Gtk.Image();
			w10.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.button4.Image = w10;
			this.hbox2.Add(this.button4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button4]));
			w11.Position = 2;
			this.table6.Add(this.hbox2);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table6[this.hbox2]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.eventbox1.Add(this.table6);
			this.vpaned1.Add(this.eventbox1);
			this.Add(this.vpaned1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 649;
			this.DefaultHeight = 252;
			this.Show();
			this.button4.Pressed += new global::System.EventHandler(this.OnButton4Pressed);
			this.button3.Pressed += new global::System.EventHandler(this.OnButton3Pressed);
		}
	}
}
