
// This file has been generated by the GUI designer. Do not modify.
namespace cSharp_basic_homework_1
{
	public partial class MainWindow
	{
		private global::Gtk.Table table1;

		private global::Gtk.Button button10;

		private global::Gtk.Button button11;

		private global::Gtk.Button button12;

		private global::Gtk.Button button7;

		private global::Gtk.Button button8;

		private global::Gtk.Button button9;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget cSharp_basic_homework_1.MainWindow
			this.Name = "cSharp_basic_homework_1.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(18));
			// Container child cSharp_basic_homework_1.MainWindow.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(2)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.button10 = new global::Gtk.Button();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.Label = global::Mono.Unix.Catalog.GetString("Problem four");
			this.table1.Add(this.button10);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.button10]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.button11 = new global::Gtk.Button();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseUnderline = true;
			this.button11.Label = global::Mono.Unix.Catalog.GetString("Problem five");
			this.table1.Add(this.button11);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.button11]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.button12 = new global::Gtk.Button();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			this.button12.Label = global::Mono.Unix.Catalog.GetString("Problem six");
			this.table1.Add(this.button12);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.button12]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.button7 = new global::Gtk.Button();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString("Problem one");
			this.table1.Add(this.button7);
			// Container child table1.Gtk.Table+TableChild
			this.button8 = new global::Gtk.Button();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString("Problem two");
			this.table1.Add(this.button8);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.button8]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.button9 = new global::Gtk.Button();
			this.button9.CanFocus = true;
			this.button9.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Relief = ((global::Gtk.ReliefStyle)(1));
			this.button9.Label = global::Mono.Unix.Catalog.GetString("Problem three");
			this.table1.Add(this.button9);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.button9]));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.table1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 585;
			this.DefaultHeight = 226;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.button9.Pressed += new global::System.EventHandler(this.OnButton9Pressed);
			this.button8.Pressed += new global::System.EventHandler(this.OnButton8Pressed);
			this.button7.Pressed += new global::System.EventHandler(this.OnButton7Pressed);
			this.button12.Pressed += new global::System.EventHandler(this.OnButton12Pressed);
			this.button11.Pressed += new global::System.EventHandler(this.OnButton11Pressed);
			this.button10.Pressed += new global::System.EventHandler(this.OnButton10Pressed);
		}
	}
}
